image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*
    expire_in: 1 day
  only:
    - dev_ci

test:
  stage: test
  script:
    - ./gradlew check

deploy:
  stage: deploy
  script:
    - echo "Deploy..."

after_script:
  - echo "End CI"