/*
 * This file is generated by jOOQ.
 */
package org.zgr.notification.sender.db.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntCommQuery implements Serializable {

    private static final long serialVersionUID = 1L;

    private String    campaignCd;
    private Long      contactId;
    private Long      creCardId;
    private Integer   offerId;
    private Date      startDate;
    private Date      endDate;
    private Time      startTime;
    private Time      endTime;
    private String    macrobrend;
    private String    mobilePhone;
    private String    messageText;
    private String    messageHeader;
    private String    deepLink;
    private String    messageUrl;
    private Long      intQueryId;
    private Timestamp intCreateDttm;
    private Timestamp intUpdateDttm;
    private String    intStatus;
    private Integer   intErrorCode;
    private String    intErrorText;
    private Integer   sasCheckFlg;

    public IntCommQuery() {}

    public IntCommQuery(IntCommQuery value) {
        this.campaignCd = value.campaignCd;
        this.contactId = value.contactId;
        this.creCardId = value.creCardId;
        this.offerId = value.offerId;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.macrobrend = value.macrobrend;
        this.mobilePhone = value.mobilePhone;
        this.messageText = value.messageText;
        this.messageHeader = value.messageHeader;
        this.deepLink = value.deepLink;
        this.messageUrl = value.messageUrl;
        this.intQueryId = value.intQueryId;
        this.intCreateDttm = value.intCreateDttm;
        this.intUpdateDttm = value.intUpdateDttm;
        this.intStatus = value.intStatus;
        this.intErrorCode = value.intErrorCode;
        this.intErrorText = value.intErrorText;
        this.sasCheckFlg = value.sasCheckFlg;
    }

    public IntCommQuery(
        String    campaignCd,
        Long      contactId,
        Long      creCardId,
        Integer   offerId,
        Date      startDate,
        Date      endDate,
        Time      startTime,
        Time      endTime,
        String    macrobrend,
        String    mobilePhone,
        String    messageText,
        String    messageHeader,
        String    deepLink,
        String    messageUrl,
        Long      intQueryId,
        Timestamp intCreateDttm,
        Timestamp intUpdateDttm,
        String    intStatus,
        Integer   intErrorCode,
        String    intErrorText,
        Integer   sasCheckFlg
    ) {
        this.campaignCd = campaignCd;
        this.contactId = contactId;
        this.creCardId = creCardId;
        this.offerId = offerId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.macrobrend = macrobrend;
        this.mobilePhone = mobilePhone;
        this.messageText = messageText;
        this.messageHeader = messageHeader;
        this.deepLink = deepLink;
        this.messageUrl = messageUrl;
        this.intQueryId = intQueryId;
        this.intCreateDttm = intCreateDttm;
        this.intUpdateDttm = intUpdateDttm;
        this.intStatus = intStatus;
        this.intErrorCode = intErrorCode;
        this.intErrorText = intErrorText;
        this.sasCheckFlg = sasCheckFlg;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.campaign_cd</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getCampaignCd() {
        return this.campaignCd;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.campaign_cd</code>.
     */
    public IntCommQuery setCampaignCd(String campaignCd) {
        this.campaignCd = campaignCd;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.contact_id</code>.
     */
    @NotNull
    public Long getContactId() {
        return this.contactId;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.contact_id</code>.
     */
    public IntCommQuery setContactId(Long contactId) {
        this.contactId = contactId;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.cre_card_id</code>.
     */
    @NotNull
    public Long getCreCardId() {
        return this.creCardId;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.cre_card_id</code>.
     */
    public IntCommQuery setCreCardId(Long creCardId) {
        this.creCardId = creCardId;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.offer_id</code>.
     */
    public Integer getOfferId() {
        return this.offerId;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.offer_id</code>.
     */
    public IntCommQuery setOfferId(Integer offerId) {
        this.offerId = offerId;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.start_date</code>.
     */
    @NotNull
    public Date getStartDate() {
        return this.startDate;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.start_date</code>.
     */
    public IntCommQuery setStartDate(Date startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.end_date</code>.
     */
    @NotNull
    public Date getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.end_date</code>.
     */
    public IntCommQuery setEndDate(Date endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.start_time</code>.
     */
    @NotNull
    public Time getStartTime() {
        return this.startTime;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.start_time</code>.
     */
    public IntCommQuery setStartTime(Time startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.end_time</code>.
     */
    @NotNull
    public Time getEndTime() {
        return this.endTime;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.end_time</code>.
     */
    public IntCommQuery setEndTime(Time endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.macrobrend</code>.
     */
    @NotNull
    @Size(max = 12)
    public String getMacrobrend() {
        return this.macrobrend;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.macrobrend</code>.
     */
    public IntCommQuery setMacrobrend(String macrobrend) {
        this.macrobrend = macrobrend;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.mobile_phone</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getMobilePhone() {
        return this.mobilePhone;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.mobile_phone</code>.
     */
    public IntCommQuery setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.message_text</code>.
     */
    @NotNull
    @Size(max = 250)
    public String getMessageText() {
        return this.messageText;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.message_text</code>.
     */
    public IntCommQuery setMessageText(String messageText) {
        this.messageText = messageText;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.message_header</code>.
     */
    @Size(max = 100)
    public String getMessageHeader() {
        return this.messageHeader;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.message_header</code>.
     */
    public IntCommQuery setMessageHeader(String messageHeader) {
        this.messageHeader = messageHeader;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.deep_link</code>.
     */
    @Size(max = 100)
    public String getDeepLink() {
        return this.deepLink;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.deep_link</code>.
     */
    public IntCommQuery setDeepLink(String deepLink) {
        this.deepLink = deepLink;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.message_url</code>.
     */
    @Size(max = 200)
    public String getMessageUrl() {
        return this.messageUrl;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.message_url</code>.
     */
    public IntCommQuery setMessageUrl(String messageUrl) {
        this.messageUrl = messageUrl;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_query_id</code>.
     */
    @NotNull
    public Long getIntQueryId() {
        return this.intQueryId;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_query_id</code>.
     */
    public IntCommQuery setIntQueryId(Long intQueryId) {
        this.intQueryId = intQueryId;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_create_dttm</code>.
     */
    @NotNull
    public Timestamp getIntCreateDttm() {
        return this.intCreateDttm;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_create_dttm</code>.
     */
    public IntCommQuery setIntCreateDttm(Timestamp intCreateDttm) {
        this.intCreateDttm = intCreateDttm;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_update_dttm</code>.
     */
    @NotNull
    public Timestamp getIntUpdateDttm() {
        return this.intUpdateDttm;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_update_dttm</code>.
     */
    public IntCommQuery setIntUpdateDttm(Timestamp intUpdateDttm) {
        this.intUpdateDttm = intUpdateDttm;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_status</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getIntStatus() {
        return this.intStatus;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_status</code>.
     */
    public IntCommQuery setIntStatus(String intStatus) {
        this.intStatus = intStatus;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_error_code</code>.
     */
    public Integer getIntErrorCode() {
        return this.intErrorCode;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_error_code</code>.
     */
    public IntCommQuery setIntErrorCode(Integer intErrorCode) {
        this.intErrorCode = intErrorCode;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_error_text</code>.
     */
    @Size(max = 200)
    public String getIntErrorText() {
        return this.intErrorText;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_error_text</code>.
     */
    public IntCommQuery setIntErrorText(String intErrorText) {
        this.intErrorText = intErrorText;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.sas_check_flg</code>.
     */
    public Integer getSasCheckFlg() {
        return this.sasCheckFlg;
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.sas_check_flg</code>.
     */
    public IntCommQuery setSasCheckFlg(Integer sasCheckFlg) {
        this.sasCheckFlg = sasCheckFlg;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IntCommQuery (");

        sb.append(campaignCd);
        sb.append(", ").append(contactId);
        sb.append(", ").append(creCardId);
        sb.append(", ").append(offerId);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(macrobrend);
        sb.append(", ").append(mobilePhone);
        sb.append(", ").append(messageText);
        sb.append(", ").append(messageHeader);
        sb.append(", ").append(deepLink);
        sb.append(", ").append(messageUrl);
        sb.append(", ").append(intQueryId);
        sb.append(", ").append(intCreateDttm);
        sb.append(", ").append(intUpdateDttm);
        sb.append(", ").append(intStatus);
        sb.append(", ").append(intErrorCode);
        sb.append(", ").append(intErrorText);
        sb.append(", ").append(sasCheckFlg);

        sb.append(")");
        return sb.toString();
    }
}
