/*
 * This file is generated by jOOQ.
 */
package org.zgr.notification.sender.db.jooq;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.zgr.notification.sender.db.jooq.tables.IntCommQuery;
import org.zgr.notification.sender.db.jooq.tables.IntCommResponse;
import org.zgr.notification.sender.db.jooq.tables.IntDeactivateList;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationSender extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>notification_sender</code>
     */
    public static final NotificationSender NOTIFICATION_SENDER = new NotificationSender();

    /**
     * The table <code>notification_sender.int_comm_query</code>.
     */
    public final IntCommQuery INT_COMM_QUERY = IntCommQuery.INT_COMM_QUERY;

    /**
     * The table <code>notification_sender.int_comm_response</code>.
     */
    public final IntCommResponse INT_COMM_RESPONSE = IntCommResponse.INT_COMM_RESPONSE;

    /**
     * The table <code>notification_sender.int_deactivate_list</code>.
     */
    public final IntDeactivateList INT_DEACTIVATE_LIST = IntDeactivateList.INT_DEACTIVATE_LIST;

    /**
     * No further instances allowed
     */
    private NotificationSender() {
        super("notification_sender", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            IntCommQuery.INT_COMM_QUERY,
            IntCommResponse.INT_COMM_RESPONSE,
            IntDeactivateList.INT_DEACTIVATE_LIST);
    }
}
