/*
 * This file is generated by jOOQ.
 */
package org.zgr.notification.sender.db.jooq;


import javax.annotation.Generated;

import org.zgr.notification.sender.db.jooq.tables.IntCommQuery;
import org.zgr.notification.sender.db.jooq.tables.IntCommResponse;
import org.zgr.notification.sender.db.jooq.tables.IntDeactivateList;


/**
 * Convenience access to all tables in notification_sender.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>notification_sender.int_comm_query</code>.
     */
    public static final IntCommQuery INT_COMM_QUERY = IntCommQuery.INT_COMM_QUERY;

    /**
     * The table <code>notification_sender.int_comm_response</code>.
     */
    public static final IntCommResponse INT_COMM_RESPONSE = IntCommResponse.INT_COMM_RESPONSE;

    /**
     * The table <code>notification_sender.int_deactivate_list</code>.
     */
    public static final IntDeactivateList INT_DEACTIVATE_LIST = IntDeactivateList.INT_DEACTIVATE_LIST;
}
