server:
  port: ${port}
spring:
  datasource:
    platform: ${platform}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_address}:${db_port}/${db_name}
    username: ${db_user}
    password: ${db_pass}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  flyway:
    enabled: false
  jooq:
    sql-dialect: postgres

notification:
  service-numbers:
    366:
      sms: ${sn_366_sms}
      push: ${sn_366_push}
    gorzdrav:
      sms: ${sn_gorzdrav_sms}
      push: ${sn_gorzdrav_push}
  send:
    url: ${send_url}
    connect-timeout-millis: 3000
    request-timeout-millis: 3000
    login: s
    password: www
    ttl: 60
    ttlUnit: MINUTES
  receive:
    mapping: /status
    delay-millis: 30000
    wait-before-send-minutes: 30
    task-limit: 100
    core-pool-size: 10
    max-pool-size: 10
    keep-alive-time: 20