server:
  port: ${port:9090}
spring:
  datasource:
    platform: ${platform:postgresql}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_address:10.241.0.127}:${db_port:5432}/${db_name:notification-service}
    username: ${db_user:postgres}
    password: ${db_pass:}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  flyway:
    enabled: false
  jooq:
    sql-dialect: postgres

notification:
  service-numbers:
    366:
      sms: ${sn_366_sms:df}
      push: ${sn_366_push:ff}
    gorzdrav:
      sms: ${sn_gorzdrav_sms:ff}
      push: ${sn_gorzdrav_push:ff}
  send:
    url: ${send_url:http://send.to}
    connect-timeout-millis: 3000
    request-timeout-millis: 3000
    login: s
    password: www
    ttl: 60
    ttlUnit: MINUTES
  receive:
    mapping: /status
    delay-millis: 30000
    wait-before-send-minutes: 30
    task-limit: 100
    core-pool-size: 10
    max-pool-size: 10
    keep-alive-time: 20