spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.241.0.127:5432/notification-service
    username: postgres
    password: ''
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  flyway:
    enabled: false
  jooq:
    sql-dialect: postgres

notification:
  send:
    url: http://www.send.to
  receive:
    mapping: /status
    delay-millis: 30000
    wait-before-send-minutes: 30