/*
 * This file is generated by jOOQ.
 */
package com.zgr.notification.sender.db.jooq.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntDeactivateList implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long      contactId;
    private Timestamp intUpdateDttm;
    private String    intStatus;

    public IntDeactivateList() {}

    public IntDeactivateList(IntDeactivateList value) {
        this.contactId = value.contactId;
        this.intUpdateDttm = value.intUpdateDttm;
        this.intStatus = value.intStatus;
    }

    public IntDeactivateList(
        Long      contactId,
        Timestamp intUpdateDttm,
        String    intStatus
    ) {
        this.contactId = contactId;
        this.intUpdateDttm = intUpdateDttm;
        this.intStatus = intStatus;
    }

    /**
     * Getter for <code>notification_sender.int_deactivate_list.contact_id</code>.
     */
    @NotNull
    public Long getContactId() {
        return this.contactId;
    }

    /**
     * Setter for <code>notification_sender.int_deactivate_list.contact_id</code>.
     */
    public IntDeactivateList setContactId(Long contactId) {
        this.contactId = contactId;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_deactivate_list.int_update_dttm</code>.
     */
    @NotNull
    public Timestamp getIntUpdateDttm() {
        return this.intUpdateDttm;
    }

    /**
     * Setter for <code>notification_sender.int_deactivate_list.int_update_dttm</code>.
     */
    public IntDeactivateList setIntUpdateDttm(Timestamp intUpdateDttm) {
        this.intUpdateDttm = intUpdateDttm;
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_deactivate_list.int_status</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getIntStatus() {
        return this.intStatus;
    }

    /**
     * Setter for <code>notification_sender.int_deactivate_list.int_status</code>.
     */
    public IntDeactivateList setIntStatus(String intStatus) {
        this.intStatus = intStatus;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IntDeactivateList (");

        sb.append(contactId);
        sb.append(", ").append(intUpdateDttm);
        sb.append(", ").append(intStatus);

        sb.append(")");
        return sb.toString();
    }
}
