/*
 * This file is generated by jOOQ.
 */
package com.zgr.notification.sender.db.jooq.tables.records;


import com.zgr.notification.sender.db.jooq.tables.IntCommQuery;
import org.jooq.Field;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntCommQueryRecord extends TableRecordImpl<IntCommQueryRecord> implements Record21<String, Long, Long, Integer, Date, Date, Time, Time, String, String, String, String, String, String, Long, Timestamp, Timestamp, String, Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notification_sender.int_comm_query.campaign_cd</code>.
     */
    public IntCommQueryRecord setCampaignCd(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.campaign_cd</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getCampaignCd() {
        return (String) get(0);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.contact_id</code>.
     */
    public IntCommQueryRecord setContactId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.contact_id</code>.
     */
    @NotNull
    public Long getContactId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.cre_card_id</code>.
     */
    public IntCommQueryRecord setCreCardId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.cre_card_id</code>.
     */
    @NotNull
    public Long getCreCardId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.offer_id</code>.
     */
    public IntCommQueryRecord setOfferId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.offer_id</code>.
     */
    public Integer getOfferId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.start_date</code>.
     */
    public IntCommQueryRecord setStartDate(Date value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.start_date</code>.
     */
    @NotNull
    public Date getStartDate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.end_date</code>.
     */
    public IntCommQueryRecord setEndDate(Date value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.end_date</code>.
     */
    @NotNull
    public Date getEndDate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.start_time</code>.
     */
    public IntCommQueryRecord setStartTime(Time value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.start_time</code>.
     */
    @NotNull
    public Time getStartTime() {
        return (Time) get(6);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.end_time</code>.
     */
    public IntCommQueryRecord setEndTime(Time value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.end_time</code>.
     */
    @NotNull
    public Time getEndTime() {
        return (Time) get(7);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.macrobrend</code>.
     */
    public IntCommQueryRecord setMacrobrend(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.macrobrend</code>.
     */
    @NotNull
    @Size(max = 12)
    public String getMacrobrend() {
        return (String) get(8);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.mobile_phone</code>.
     */
    public IntCommQueryRecord setMobilePhone(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.mobile_phone</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getMobilePhone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.message_text</code>.
     */
    public IntCommQueryRecord setMessageText(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.message_text</code>.
     */
    @NotNull
    @Size(max = 250)
    public String getMessageText() {
        return (String) get(10);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.message_header</code>.
     */
    public IntCommQueryRecord setMessageHeader(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.message_header</code>.
     */
    @Size(max = 100)
    public String getMessageHeader() {
        return (String) get(11);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.deep_link</code>.
     */
    public IntCommQueryRecord setDeepLink(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.deep_link</code>.
     */
    @Size(max = 100)
    public String getDeepLink() {
        return (String) get(12);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.message_url</code>.
     */
    public IntCommQueryRecord setMessageUrl(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.message_url</code>.
     */
    @Size(max = 200)
    public String getMessageUrl() {
        return (String) get(13);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_query_id</code>.
     */
    public IntCommQueryRecord setIntQueryId(Long value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_query_id</code>.
     */
    public Long getIntQueryId() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_create_dttm</code>.
     */
    public IntCommQueryRecord setIntCreateDttm(Timestamp value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_create_dttm</code>.
     */
    @NotNull
    public Timestamp getIntCreateDttm() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_update_dttm</code>.
     */
    public IntCommQueryRecord setIntUpdateDttm(Timestamp value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_update_dttm</code>.
     */
    @NotNull
    public Timestamp getIntUpdateDttm() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_status</code>.
     */
    public IntCommQueryRecord setIntStatus(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_status</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getIntStatus() {
        return (String) get(17);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_error_code</code>.
     */
    public IntCommQueryRecord setIntErrorCode(Integer value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_error_code</code>.
     */
    public Integer getIntErrorCode() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.int_error_text</code>.
     */
    public IntCommQueryRecord setIntErrorText(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.int_error_text</code>.
     */
    @Size(max = 200)
    public String getIntErrorText() {
        return (String) get(19);
    }

    /**
     * Setter for <code>notification_sender.int_comm_query.sas_check_flg</code>.
     */
    public IntCommQueryRecord setSasCheckFlg(Integer value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_query.sas_check_flg</code>.
     */
    public Integer getSasCheckFlg() {
        return (Integer) get(20);
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<String, Long, Long, Integer, Date, Date, Time, Time, String, String, String, String, String, String, Long, Timestamp, Timestamp, String, Integer, String, Integer> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<String, Long, Long, Integer, Date, Date, Time, Time, String, String, String, String, String, String, Long, Timestamp, Timestamp, String, Integer, String, Integer> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return IntCommQuery.INT_COMM_QUERY.CAMPAIGN_CD;
    }

    @Override
    public Field<Long> field2() {
        return IntCommQuery.INT_COMM_QUERY.CONTACT_ID;
    }

    @Override
    public Field<Long> field3() {
        return IntCommQuery.INT_COMM_QUERY.CRE_CARD_ID;
    }

    @Override
    public Field<Integer> field4() {
        return IntCommQuery.INT_COMM_QUERY.OFFER_ID;
    }

    @Override
    public Field<Date> field5() {
        return IntCommQuery.INT_COMM_QUERY.START_DATE;
    }

    @Override
    public Field<Date> field6() {
        return IntCommQuery.INT_COMM_QUERY.END_DATE;
    }

    @Override
    public Field<Time> field7() {
        return IntCommQuery.INT_COMM_QUERY.START_TIME;
    }

    @Override
    public Field<Time> field8() {
        return IntCommQuery.INT_COMM_QUERY.END_TIME;
    }

    @Override
    public Field<String> field9() {
        return IntCommQuery.INT_COMM_QUERY.MACROBREND;
    }

    @Override
    public Field<String> field10() {
        return IntCommQuery.INT_COMM_QUERY.MOBILE_PHONE;
    }

    @Override
    public Field<String> field11() {
        return IntCommQuery.INT_COMM_QUERY.MESSAGE_TEXT;
    }

    @Override
    public Field<String> field12() {
        return IntCommQuery.INT_COMM_QUERY.MESSAGE_HEADER;
    }

    @Override
    public Field<String> field13() {
        return IntCommQuery.INT_COMM_QUERY.DEEP_LINK;
    }

    @Override
    public Field<String> field14() {
        return IntCommQuery.INT_COMM_QUERY.MESSAGE_URL;
    }

    @Override
    public Field<Long> field15() {
        return IntCommQuery.INT_COMM_QUERY.INT_QUERY_ID;
    }

    @Override
    public Field<Timestamp> field16() {
        return IntCommQuery.INT_COMM_QUERY.INT_CREATE_DTTM;
    }

    @Override
    public Field<Timestamp> field17() {
        return IntCommQuery.INT_COMM_QUERY.INT_UPDATE_DTTM;
    }

    @Override
    public Field<String> field18() {
        return IntCommQuery.INT_COMM_QUERY.INT_STATUS;
    }

    @Override
    public Field<Integer> field19() {
        return IntCommQuery.INT_COMM_QUERY.INT_ERROR_CODE;
    }

    @Override
    public Field<String> field20() {
        return IntCommQuery.INT_COMM_QUERY.INT_ERROR_TEXT;
    }

    @Override
    public Field<Integer> field21() {
        return IntCommQuery.INT_COMM_QUERY.SAS_CHECK_FLG;
    }

    @Override
    public String component1() {
        return getCampaignCd();
    }

    @Override
    public Long component2() {
        return getContactId();
    }

    @Override
    public Long component3() {
        return getCreCardId();
    }

    @Override
    public Integer component4() {
        return getOfferId();
    }

    @Override
    public Date component5() {
        return getStartDate();
    }

    @Override
    public Date component6() {
        return getEndDate();
    }

    @Override
    public Time component7() {
        return getStartTime();
    }

    @Override
    public Time component8() {
        return getEndTime();
    }

    @Override
    public String component9() {
        return getMacrobrend();
    }

    @Override
    public String component10() {
        return getMobilePhone();
    }

    @Override
    public String component11() {
        return getMessageText();
    }

    @Override
    public String component12() {
        return getMessageHeader();
    }

    @Override
    public String component13() {
        return getDeepLink();
    }

    @Override
    public String component14() {
        return getMessageUrl();
    }

    @Override
    public Long component15() {
        return getIntQueryId();
    }

    @Override
    public Timestamp component16() {
        return getIntCreateDttm();
    }

    @Override
    public Timestamp component17() {
        return getIntUpdateDttm();
    }

    @Override
    public String component18() {
        return getIntStatus();
    }

    @Override
    public Integer component19() {
        return getIntErrorCode();
    }

    @Override
    public String component20() {
        return getIntErrorText();
    }

    @Override
    public Integer component21() {
        return getSasCheckFlg();
    }

    @Override
    public String value1() {
        return getCampaignCd();
    }

    @Override
    public Long value2() {
        return getContactId();
    }

    @Override
    public Long value3() {
        return getCreCardId();
    }

    @Override
    public Integer value4() {
        return getOfferId();
    }

    @Override
    public Date value5() {
        return getStartDate();
    }

    @Override
    public Date value6() {
        return getEndDate();
    }

    @Override
    public Time value7() {
        return getStartTime();
    }

    @Override
    public Time value8() {
        return getEndTime();
    }

    @Override
    public String value9() {
        return getMacrobrend();
    }

    @Override
    public String value10() {
        return getMobilePhone();
    }

    @Override
    public String value11() {
        return getMessageText();
    }

    @Override
    public String value12() {
        return getMessageHeader();
    }

    @Override
    public String value13() {
        return getDeepLink();
    }

    @Override
    public String value14() {
        return getMessageUrl();
    }

    @Override
    public Long value15() {
        return getIntQueryId();
    }

    @Override
    public Timestamp value16() {
        return getIntCreateDttm();
    }

    @Override
    public Timestamp value17() {
        return getIntUpdateDttm();
    }

    @Override
    public String value18() {
        return getIntStatus();
    }

    @Override
    public Integer value19() {
        return getIntErrorCode();
    }

    @Override
    public String value20() {
        return getIntErrorText();
    }

    @Override
    public Integer value21() {
        return getSasCheckFlg();
    }

    @Override
    public IntCommQueryRecord value1(String value) {
        setCampaignCd(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value2(Long value) {
        setContactId(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value3(Long value) {
        setCreCardId(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value4(Integer value) {
        setOfferId(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value5(Date value) {
        setStartDate(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value6(Date value) {
        setEndDate(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value7(Time value) {
        setStartTime(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value8(Time value) {
        setEndTime(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value9(String value) {
        setMacrobrend(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value10(String value) {
        setMobilePhone(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value11(String value) {
        setMessageText(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value12(String value) {
        setMessageHeader(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value13(String value) {
        setDeepLink(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value14(String value) {
        setMessageUrl(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value15(Long value) {
        setIntQueryId(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value16(Timestamp value) {
        setIntCreateDttm(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value17(Timestamp value) {
        setIntUpdateDttm(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value18(String value) {
        setIntStatus(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value19(Integer value) {
        setIntErrorCode(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value20(String value) {
        setIntErrorText(value);
        return this;
    }

    @Override
    public IntCommQueryRecord value21(Integer value) {
        setSasCheckFlg(value);
        return this;
    }

    @Override
    public IntCommQueryRecord values(String value1, Long value2, Long value3, Integer value4, Date value5, Date value6, Time value7, Time value8, String value9, String value10, String value11, String value12, String value13, String value14, Long value15, Timestamp value16, Timestamp value17, String value18, Integer value19, String value20, Integer value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntCommQueryRecord
     */
    public IntCommQueryRecord() {
        super(IntCommQuery.INT_COMM_QUERY);
    }

    /**
     * Create a detached, initialised IntCommQueryRecord
     */
    public IntCommQueryRecord(String campaignCd, Long contactId, Long creCardId, Integer offerId, Date startDate, Date endDate, Time startTime, Time endTime, String macrobrend, String mobilePhone, String messageText, String messageHeader, String deepLink, String messageUrl, Long intQueryId, Timestamp intCreateDttm, Timestamp intUpdateDttm, String intStatus, Integer intErrorCode, String intErrorText, Integer sasCheckFlg) {
        super(IntCommQuery.INT_COMM_QUERY);

        setCampaignCd(campaignCd);
        setContactId(contactId);
        setCreCardId(creCardId);
        setOfferId(offerId);
        setStartDate(startDate);
        setEndDate(endDate);
        setStartTime(startTime);
        setEndTime(endTime);
        setMacrobrend(macrobrend);
        setMobilePhone(mobilePhone);
        setMessageText(messageText);
        setMessageHeader(messageHeader);
        setDeepLink(deepLink);
        setMessageUrl(messageUrl);
        setIntQueryId(intQueryId);
        setIntCreateDttm(intCreateDttm);
        setIntUpdateDttm(intUpdateDttm);
        setIntStatus(intStatus);
        setIntErrorCode(intErrorCode);
        setIntErrorText(intErrorText);
        setSasCheckFlg(sasCheckFlg);
    }
}
