/*
 * This file is generated by jOOQ.
 */
package org.zgr.notification.sender.db.jooq.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;
import org.zgr.notification.sender.db.jooq.tables.IntCommResponse;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntCommResponseRecord extends TableRecordImpl<IntCommResponseRecord> implements Record10<Long, String, String, Integer, BigDecimal, Integer, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notification_sender.int_comm_response.contact_id</code>.
     */
    public IntCommResponseRecord setContactId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.contact_id</code>.
     */
    @NotNull
    public Long getContactId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.response_nm</code>.
     */
    public IntCommResponseRecord setResponseNm(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.response_nm</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getResponseNm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.message_type</code>.
     */
    public IntCommResponseRecord setMessageType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.message_type</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getMessageType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.part_count</code>.
     */
    public IntCommResponseRecord setPartCount(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.part_count</code>.
     */
    public Integer getPartCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.comm_cost</code>.
     */
    public IntCommResponseRecord setCommCost(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.comm_cost</code>.
     */
    @NotNull
    public BigDecimal getCommCost() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.error_code</code>.
     */
    public IntCommResponseRecord setErrorCode(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.error_code</code>.
     */
    @NotNull
    public Integer getErrorCode() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.error_text</code>.
     */
    public IntCommResponseRecord setErrorText(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.error_text</code>.
     */
    @Size(max = 200)
    public String getErrorText() {
        return (String) get(6);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.response_dttm</code>.
     */
    public IntCommResponseRecord setResponseDttm(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.response_dttm</code>.
     */
    @NotNull
    public Timestamp getResponseDttm() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.int_update_dttm</code>.
     */
    public IntCommResponseRecord setIntUpdateDttm(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.int_update_dttm</code>.
     */
    @NotNull
    public Timestamp getIntUpdateDttm() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>notification_sender.int_comm_response.int_status</code>.
     */
    public IntCommResponseRecord setIntStatus(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_comm_response.int_status</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getIntStatus() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, Integer, BigDecimal, Integer, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, Integer, BigDecimal, Integer, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IntCommResponse.INT_COMM_RESPONSE.CONTACT_ID;
    }

    @Override
    public Field<String> field2() {
        return IntCommResponse.INT_COMM_RESPONSE.RESPONSE_NM;
    }

    @Override
    public Field<String> field3() {
        return IntCommResponse.INT_COMM_RESPONSE.MESSAGE_TYPE;
    }

    @Override
    public Field<Integer> field4() {
        return IntCommResponse.INT_COMM_RESPONSE.PART_COUNT;
    }

    @Override
    public Field<BigDecimal> field5() {
        return IntCommResponse.INT_COMM_RESPONSE.COMM_COST;
    }

    @Override
    public Field<Integer> field6() {
        return IntCommResponse.INT_COMM_RESPONSE.ERROR_CODE;
    }

    @Override
    public Field<String> field7() {
        return IntCommResponse.INT_COMM_RESPONSE.ERROR_TEXT;
    }

    @Override
    public Field<Timestamp> field8() {
        return IntCommResponse.INT_COMM_RESPONSE.RESPONSE_DTTM;
    }

    @Override
    public Field<Timestamp> field9() {
        return IntCommResponse.INT_COMM_RESPONSE.INT_UPDATE_DTTM;
    }

    @Override
    public Field<String> field10() {
        return IntCommResponse.INT_COMM_RESPONSE.INT_STATUS;
    }

    @Override
    public Long component1() {
        return getContactId();
    }

    @Override
    public String component2() {
        return getResponseNm();
    }

    @Override
    public String component3() {
        return getMessageType();
    }

    @Override
    public Integer component4() {
        return getPartCount();
    }

    @Override
    public BigDecimal component5() {
        return getCommCost();
    }

    @Override
    public Integer component6() {
        return getErrorCode();
    }

    @Override
    public String component7() {
        return getErrorText();
    }

    @Override
    public Timestamp component8() {
        return getResponseDttm();
    }

    @Override
    public Timestamp component9() {
        return getIntUpdateDttm();
    }

    @Override
    public String component10() {
        return getIntStatus();
    }

    @Override
    public Long value1() {
        return getContactId();
    }

    @Override
    public String value2() {
        return getResponseNm();
    }

    @Override
    public String value3() {
        return getMessageType();
    }

    @Override
    public Integer value4() {
        return getPartCount();
    }

    @Override
    public BigDecimal value5() {
        return getCommCost();
    }

    @Override
    public Integer value6() {
        return getErrorCode();
    }

    @Override
    public String value7() {
        return getErrorText();
    }

    @Override
    public Timestamp value8() {
        return getResponseDttm();
    }

    @Override
    public Timestamp value9() {
        return getIntUpdateDttm();
    }

    @Override
    public String value10() {
        return getIntStatus();
    }

    @Override
    public IntCommResponseRecord value1(Long value) {
        setContactId(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value2(String value) {
        setResponseNm(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value3(String value) {
        setMessageType(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value4(Integer value) {
        setPartCount(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value5(BigDecimal value) {
        setCommCost(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value6(Integer value) {
        setErrorCode(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value7(String value) {
        setErrorText(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value8(Timestamp value) {
        setResponseDttm(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value9(Timestamp value) {
        setIntUpdateDttm(value);
        return this;
    }

    @Override
    public IntCommResponseRecord value10(String value) {
        setIntStatus(value);
        return this;
    }

    @Override
    public IntCommResponseRecord values(Long value1, String value2, String value3, Integer value4, BigDecimal value5, Integer value6, String value7, Timestamp value8, Timestamp value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntCommResponseRecord
     */
    public IntCommResponseRecord() {
        super(IntCommResponse.INT_COMM_RESPONSE);
    }

    /**
     * Create a detached, initialised IntCommResponseRecord
     */
    public IntCommResponseRecord(Long contactId, String responseNm, String messageType, Integer partCount, BigDecimal commCost, Integer errorCode, String errorText, Timestamp responseDttm, Timestamp intUpdateDttm, String intStatus) {
        super(IntCommResponse.INT_COMM_RESPONSE);

        setContactId(contactId);
        setResponseNm(responseNm);
        setMessageType(messageType);
        setPartCount(partCount);
        setCommCost(commCost);
        setErrorCode(errorCode);
        setErrorText(errorText);
        setResponseDttm(responseDttm);
        setIntUpdateDttm(intUpdateDttm);
        setIntStatus(intStatus);
    }
}
