/*
 * This file is generated by jOOQ.
 */
package org.zgr.notification.sender.db.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.zgr.notification.sender.db.jooq.tables.IntDeactivateList;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IntDeactivateListRecord extends TableRecordImpl<IntDeactivateListRecord> implements Record3<Long, Timestamp, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>notification_sender.int_deactivate_list.contact_id</code>.
     */
    public IntDeactivateListRecord setContactId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_deactivate_list.contact_id</code>.
     */
    @NotNull
    public Long getContactId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>notification_sender.int_deactivate_list.int_update_dttm</code>.
     */
    public IntDeactivateListRecord setIntUpdateDttm(Timestamp value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_deactivate_list.int_update_dttm</code>.
     */
    @NotNull
    public Timestamp getIntUpdateDttm() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>notification_sender.int_deactivate_list.int_status</code>.
     */
    public IntDeactivateListRecord setIntStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>notification_sender.int_deactivate_list.int_status</code>.
     */
    @NotNull
    @Size(max = 10)
    public String getIntStatus() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Timestamp, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Timestamp, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return IntDeactivateList.INT_DEACTIVATE_LIST.CONTACT_ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return IntDeactivateList.INT_DEACTIVATE_LIST.INT_UPDATE_DTTM;
    }

    @Override
    public Field<String> field3() {
        return IntDeactivateList.INT_DEACTIVATE_LIST.INT_STATUS;
    }

    @Override
    public Long component1() {
        return getContactId();
    }

    @Override
    public Timestamp component2() {
        return getIntUpdateDttm();
    }

    @Override
    public String component3() {
        return getIntStatus();
    }

    @Override
    public Long value1() {
        return getContactId();
    }

    @Override
    public Timestamp value2() {
        return getIntUpdateDttm();
    }

    @Override
    public String value3() {
        return getIntStatus();
    }

    @Override
    public IntDeactivateListRecord value1(Long value) {
        setContactId(value);
        return this;
    }

    @Override
    public IntDeactivateListRecord value2(Timestamp value) {
        setIntUpdateDttm(value);
        return this;
    }

    @Override
    public IntDeactivateListRecord value3(String value) {
        setIntStatus(value);
        return this;
    }

    @Override
    public IntDeactivateListRecord values(Long value1, Timestamp value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IntDeactivateListRecord
     */
    public IntDeactivateListRecord() {
        super(IntDeactivateList.INT_DEACTIVATE_LIST);
    }

    /**
     * Create a detached, initialised IntDeactivateListRecord
     */
    public IntDeactivateListRecord(Long contactId, Timestamp intUpdateDttm, String intStatus) {
        super(IntDeactivateList.INT_DEACTIVATE_LIST);

        setContactId(contactId);
        setIntUpdateDttm(intUpdateDttm);
        setIntStatus(intStatus);
    }
}
